#
# Generated by jianxi(mabeijianxi@gmail.com)
# Created by jianxi.
# DateTime: 2018/8/26 下午3:50
#
import sys
import os
from PIL import Image
from PIL import ImageChops

inFileHome = r"D:\DataCenter\PycharmProjects\my_tools\validate_code\images\out"
outFileHome = r"D:\DataCenter\PycharmProjects\my_tools\validate_code\images\out"

def crop(parentFile,fileName):
    image = Image.open(parentFile+'/' +fileName)
    print(image.mode)
    image = image.convert('RGBA')
    print(image.mode)
    red, green, blue, alpha = image.split()
    print(alpha)
    width = image.size[0]
    height = image.size[1]

    print (width)
    print (height)

    def getTop():
        for i in range(height):
            for j in range(width):
                color = alpha.getpixel((j,i))
                if not color==0:
                    top = i
                    return i
    def getBot():
        for i in range(height-1,-1,-1):
            print (i)
            for j in range(width):
                color = alpha.getpixel((j,i))
                if not color==0:
                    bot = i
                    return i
    def getLeft():
        for i in range(width):
            for j in range(height):
                color = alpha.getpixel((i,j))
                if not color==0:
                    left = i
                    return i
    def getRight():
        for i in range(width-1,-1,-1):
            for j in range(height):
                color = alpha.getpixel((i,j))
                if not color==0:
                    right = i
                    return i
    left = getLeft()
    top = getTop()
    right = getRight()
    bot = getBot()

    if not left:
        left = 0
    if not top:
        top = 0
    if not right:
        right = width
    if not bot:
        bot = height


    print (left)
    print (top)
    print (right)
    print (bot)

    rect = (left,top,right,bot)
    print (rect)
    new_image = image.crop(rect)
    new_image.save(outFileHome+"/"+fileName,"PNG")


for root,dirs,files in os.walk(inFileHome):
    for file in files:
        if os.path.splitext(file)[1] == ".png":
            crop(inFileHome,file)
